[env:esp32doit-devkit-v1]
platform  = espressif32
board     = esp32doit-devkit-v1
framework = arduino

monitor_speed   = 115200
upload_speed    = 921600

; ArduinoJson v6 requerido — StaticJsonDocument eliminado en v7
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.5
    links2004/WebSockets  @ ^2.4.1
